name: Update All GameLibs

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 * * *"

jobs:
  list-games:
    name: List games in repository 
    runs-on: ubuntu-latest
    outputs: 
      games: ${{ steps.list.outputs.games }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: List games
        id: list
        uses: ./.github/actions/listGames
          
  dispatch-game-update-checks:
    needs: list-games
    if: ${{ needs.list-games.outputs.games != '[]' && needs.list-games.outputs.games != '' }}
    strategy: 
      matrix:
        game: ${{ fromJson(needs.list-games.outputs.games) }}
      fail-fast: false
    uses: ./.github/workflows/checkGameForUpdates.yml
    with:
      game: ${{ matrix.game }}
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
      